services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "loader_app_db"
      POSTGRES_USER: "loader_app"
      POSTGRES_PASSWORD: "loader_app"
    ports:
      - "5432:5432"
